
<!-- saved from url=(0043)https://www.lottovip.com/lang.js?1563160022 -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>var lang = {
vailbank : 'กรุณาเลือกธนาคาร',
vailnamebank : 'กรุณากรอก ชื่อ-นาม สกุลตามหน้าสมุดบัญชี',
please_select_channel_deposit_js : 'กรุณาเลือกช่องทางการโอนเงิน',
please_enter_price_deposit_js : 'กรุณาใส่จำนวนเงิน',
limit_per_time : 'ฝากขั้นต่ำ 20 และไม่เกิน 1,000,000 บาท ต่อครั้ง',
technical_crash : 'เนื่องจากมีปัญหาด้านเทคนิค กรุณาติดต่อแอดมิน หรือ ลองใหม่อีกครั้ง',
send_success_deposit_js : 'ส่งข้อมูลสำเร็จ',
please_wait_queue_deposit_js : 'การแจ้งโอนครั้งล่าสุดคุณ รอคิวตรวจสอบ',
inform_last_deposit_js : 'การแจ้งโอนครั้งล่าสุดคุณ รอยอดจากธนาคาร',
inform_transfer_wait_add_deposit_js : 'การแจ้งโอนครั้งล่าสุดคุณ รอเพิ่มเคดิต',
inform_transfer_unsuccess_deposit_js : 'การแจ้งโอนไม่สำเร็จ',
min_bet_conditions_pagebet_js : 'ขั้นต่ำในการแทงไม่ตรงตามเงื่อนไขที่กำหนด',
bet_over_per_member_pagebet_js : 'ยอดแทงเกินกว่ายอดจำกัดจำนวนการแทงต่อสมาชิก',
change_rate_pay_pagebet_js : 'เรทการจ่ายมีการเปลี่ยนแปลง โปรดยืนยันอีกครั้ง',
add_number_success_pagebet_js : ' เพิ่ม เลขเรียบร้อยแล้ว',
please_test_pagebet_js : ' กรุณาลองใหม่อีกครั้ง',
enter_5_digits_pagebet_js : ' กรุณากรอกเลขให้ครบ 5 หลัก',
enter_lang_a_z : 'กรุณาใช้ภาษาที่ถูกต้องและห้ามเคาะวรรค a-z A-Z 0-9',
no_lang_thai : 'กรุณาใช้ภาษาที่ถูกต้องและห้ามเคาะวรรคและห้ามใช้ภาษาไทย',
pass_new_newconfirm_not_match : 'รหัสผ่านใหม่ และ ยืนยันรหัสผ่านใหม่ ไม่ตรงกัน',
add_success_wait_ap_settings_js : 'เพิ่มบัญชีสำเร็จ รอการตรวจสอบ',
bank_dup_settings_js : 'เลขบัญชีซ้ำ ไม่สามารถเพิ่มได้',
enter_bank_num_settings_js : 'กรุณากรอก เลขบัญชี',
enter_bank_num2_settings_js : 'กรุณากรอก เลขบัญชียืนยัน',
bank_num_not_match_settings_js : 'กรุณาใส่เลขบัญชี และ เลขบัญชียืนยันให้ตรงกัน',
please_enter_price_withdraw_js : 'กรุณาใส่จำนวนเงิน',
withdraw_limit_per_time : 'ถอนขั้นต่ำ 100 และไม่เกิน 50,000 บาท ต่อครั้ง',
balance_not_enough : 'ยอดเงินของคุณไม่เพียงพอ',
insert_js : 'เพิ่ม',
list_program_js : 'รายการ',
teng_bon_1_js : 'วิ่งบน',
teng_lang_1_js : 'วิ่งล่าง',
teng_bon_2_js : 'สองตัวบน',
teng_lang_2_js : 'สองตัวล่าง',
teng_bon_3_js : 'สามตัวบน',
tode_3_js : 'สามตัวโต๊ด',
teng_lang_nha_3_js : 'สามตัวหน้า',
teng_lang_3_js : 'สามตัวล่าง',
list_program_all_js : 'รายการแทงทั้งหมด',
min_is_input_js : 'ราคาต่ำสุดที่ใส่ได้คือ',
max_is_input_js : 'ราคาสูงสุดที่ใส่ได้คือ',
send_poy_success_js : 'ส่งโพยเรียบร้อยแล้ว',
pass_not_match : '',
settings_addbank_vaild : 'กรุณากรอกชื่อและเลขบัญชีให้ถูกต้อง และ เลขบัญชีต้องไม่เกิน 12 หลัก',
copy_text_af : 'คัดลอกลิงค์แนะนำเรียบร้อยแล้ว',
copy_text_bank : 'คัดลอกเรียบร้อยแล้ว',
limit_time_deposit : 'ธนาคารปิดปรับปรุงประจำวัน 23.00 - 0.10 โปรดรอทำรายการฝากใหม่นอกเวลาดังกล่าว',
send_lottery_success_js : 'ส่งหวยชุดสำเร็จ',
send_lottery_nomoney_js : 'จำนวนเงินของคุณไม่พอ',
send_lottery_notopen_js : 'หวยลาวยังไม่เปิดในตอนนี้',
send_lottery_success_hy_js : 'ส่งหวยชุดสำเร็จ',
send_lottery_nomoney_hy_js : 'จำนวนเงินของคุณไม่พอ',
send_lottery_notopen_hy_js : 'หวยลาวยังไม่เปิดในตอนนี้',
deposit_too_fast : 'กรุณารอ 3 นาที หลังจากโอนเงินแล้ว จึงจะสามารถแจ้งโอนได้',
send_jp_success_js : 'ส่งเลข Jackpot สำเร็จ',
send_jp_noreward_js : 'จำนวนคะแนน Reward ของท่านไม่เพียงพอ',
create_yingchub_success_js : 'สร้างห้องเป่ายิงฉุบสำเร็จ',
send_yingchub_notopen_js : 'ระบบเป่ายิงฉุบยังไม่เปิดในตอนนี้',
send_yingchub_nomoney_js : 'จำนวนเงินของคุณไม่พอ',
send_lottery_lotterylimit_js : 'เลขชุดนี้เต็มแล้ว กรุณาเปลี่ยนเลขชุดใหม่'
}
</body></html>